# Define an array of symbolic link sources and targets
$(pwd)/starship/starship.toml:$HOME/.config/starship.toml
$(pwd)/nvim:$HOME/.config/nvim
$(pwd)/ghostty:$HOME/.config/ghostty
$(pwd)/ghostty:/Users/tutu/Library/Application Support/com.mitchellh.ghostty
$(pwd)/ssh/config:$HOME/.ssh/config
$(pwd)/Rectangle/RectangleConfig.json:$HOME/Library/Application Support/Rectangle/RectangleConfig.json
$(pwd)/tmux/:$HOME/.config/tmux
$(pwd)/superfile/config.toml:$HOME/Library/Application Support/superfile/config.toml
$(pwd)/superfile/hotkeys.toml:$HOME/Library/Application Support/superfile/hotkeys.toml
