[mgr]

prepend_keymap = [
	# Override default H/L with C-o/Tab for back/forward
	{ on = "H",      run = "noop" },
	{ on = "L",      run = "noop" },
	{ on = "<C-o>",  run = "back",    desc = "Back to previous directory" },
	{ on = "<C-i>",  run = "forward", desc = "Forward to next directory" },

	# Override default C-a select all with A-a
	{ on = "<C-a>", run = "noop" },
	{ on = "<A-a>", run = "toggle_all --state=on", desc = "Select all files" },

	# Override default K/J seek with C-A-k/C-A-j
	{ on = "K",         run = "noop" },
	{ on = "J",         run = "noop" },
	{ on = "<C-k>",   run = "seek -10", desc = "Seek up 10L in the preview" },
	{ on = "<C-j>",   run = "seek 10",  desc = "Seek down 10L in the preview" },

	# Override default Tab spot with \
	# { on = "<Tab>", run = "noop" },
	{ on = "\\",    run = "spot", desc = "Spot hovered file" },

	# Override default tt tab create with single t
	# { on = [ "t", "t" ], run = "noop" },
	# { on = "t",           run = "tab_create --current", desc = "Create a new tab with CWD" },

	# Override default ~/F1 help with ?
	{ on = "~",     run = "noop" },
	{ on = "<F1>",  run = "noop" },
	{ on = "?",     run = "help", desc = "Open help" },
]

append_keymap = [
	{ on = "e", run = 'shell "nvim --server /tmp/lpt-nvim.sock --remote $@"', desc = "Open selected files in existing Neovim session" },
]

[spot]

prepend_keymap = [
	# Override default Tab close with \
	# { on = "<Tab>", run = "noop" },
	{ on = "\\",    run = "close", desc = "Close the spot" },
]
