# editor
brew "nvim"                  # Neovim 编辑器
# brew "helix"
brew "npm"                   # need to install mason plugin

# dotfiles manage
brew "stow"                  # dotfiles 管理

# shell util
brew "starship"              # 星舰终端提示符
brew "eza"                   # ls 的现代化替代
brew "bat"                   # cat 的彩色高亮增强版
brew "yazi"                  # file manager
brew "fd"                    # file searching
brew "ripgrep"               # file content searching
brew "file"                  # file type detection
brew "jq"                    # json preview
brew "yq"                    # command-line YAML, JSON, XML, CSV, TOML, HCL and properties processor
brew "7-Zip"                 # archive extraction and preview
brew "fzf"                   # fuzzy finder
brew "zoxide"                # jump cd
brew "atuin"                 # history sync
brew "tokei"                 # LOC count

# terminal multiplier
brew "tmux"                  # 终端复用器
brew "tmuxinator"            # tmux tool

# debug
brew "gdb"                   # gdb debugger

# cheat sheet
brew "thefuck"               # 历史命令纠错
brew "tldr"                  # tldr 文档查看

# git tool
brew "lazygit"               # 交互式 Git TUI
brew "git-delta"             # enhanced diff for git,bat...
brew "onefetch"              # git repo info
# brew "tig"                   # text-mode interface for Git (for git log)
# brew "gitui"                 # fast but in developed, maybe use later

# docker
# brew "lazydocker"            # 交互式 docker TUI

# secret
brew "sops"
brew "age"

# ai tool
brew "code2prompt"

# venv
brew "uv"

# benchmark
brew "hyperfine"

# system info
brew "fastfetch"             # maintained neofetch
brew "btop"                  # better top
brew "pstree"                # 以树状图显示进程
