# Use zsh as default
set -g default-shell /bin/zsh

# Enable 256-color and true-color (24-bit) support in tmux
set -g default-terminal "screen-256color" # Set terminal type for 256-color support
set -ga terminal-overrides ",*256col*:Tc" # Override to enable true-color for compatible terminals
# cursor type
# set -ga terminal-overrides ',*:Ss=\E[5 q:Se=\E[2 q'

# General
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove delay for exiting insert mode with ESC in Neovim
set -g history-limit 1000000    # Increase history size (from 2,000)
set -g mouse on                 # Enable mouse support
set -g status-interval 3        # Update the status bar every 3 seconds (default: 15 seconds)
set -g allow-passthrough on   # Allow programs in the pane to bypass tmux (e.g. for image preview)

source ~/.config/tmux/hotkey.conf

# Startwindows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed
set -g automatic-rename on

# # Title Bar
# allow the title bar to adapt to whatever host you connect to
set -g set-titles on
# set -g set-titles-string "#W"

# Resurrect
set -g @resurrect-capture-pane-contents 'on'
# Last saved environment is automatically restored when tmux is started.
set -g @continuum-save-interval '2'
set -g @continuum-restore 'on'

########## THEME

# load theme
source ~/.config/tmux/theme.conf

# Statusline configs
source ~/.config/tmux/statusline.conf

########## THEME

# Configure Tmux Plugin Manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

# Bootstrap TPM
if 'test ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm"' {
  run 'mkdir -p "${TMUX_PLUGIN_MANAGER_PATH}"'
  run 'git clone https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"'
  run '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

# List of plugins
set -g @plugin 'tmux-plugins/tpm' # Tmux Plugin Manager
set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux
set -g @plugin 'alexwforsythe/tmux-which-key' # prefix + space
# set -g @plugin 'thewtex/tmux-mem-cpu-load' # CPU and memory info
# set -g @plugin 'tmux-plugins/tmux-sensible' # Tmux Sensible defaults
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Restore tmux environment after system restart
set -g @plugin 'tmux-plugins/tmux-continuum' # continuous saving of tmux environment, auto start and restore (relies on the save state of resurrect)
set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'xamut/tmux-weather'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# NOTE:
# - To apply theme changes: tmux kill-server && rm -rf /tmp/tmux-*
